dist: trusty
# We use the generic language to avoid Travis overwriting the CC and CXX
# environment variables. See https://stackoverflow.com/questions/35110123/travis-ci-with-c14-and-linux.
language: generic

# Stop Leak Sanitizer from crashing.
sudo: true

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CC=gcc-4.9 CXX=g++-4.9

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.5
          packages:
            - clang-3.5
      env: CC=clang-3.5 CXX=clang++-3.5

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: CC=gcc-8 CXX=g++-8

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
      env: CC=clang-7 CXX=clang++-7

    - os: osx
      env: CC=clang CXX=clang++

script:
  - cmake .
      -DCMAKE_BUILD_TYPE=Debug
      -DBUILD_SHARED_LIBS=ON
      -DREPROCXX=ON
      -DREPROC_TESTS=ON
      -DREPROC_EXAMPLES=ON
      -DREPROC_INSTALL=ON
      -DREPROC_CI=ON
      -DREPROC_TIDY=ON
      -DREPROC_FORMAT=ON
      -DREPROC_SANITIZERS=ON
  - cmake --build . -- -j 2
  - cmake --build . --target reproc-run-tests
  # Make sure examples don't crash or return a non-zero exit code.
  - ./examples/git-status > /dev/null
  - ./examples/cmake-help > /dev/null
