dist: xenial
# We use the generic language to prevent Travis from overwriting the CC and CXX
# environment variables. See https://stackoverflow.com/questions/35110123/travis-ci-with-c14-and-linux.
language: generic

# Leak Sanitizer crashes if we don't run with root priviliges.
sudo: true

notifications:
  email: false

matrix:
  fast_finish: true

env: REPROC_TIDY=ON

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CC=gcc-4.9 CXX=g++-4.9

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.5
          packages:
            - clang-3.5
      env: CC=clang-3.5 CXX=clang++-3.5

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: CC=gcc-8 CXX=g++-8

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
      env: CC=clang-7 CXX=clang++-7

    - os: osx
      env: CC=clang CXX=clang++ REPROC_TIDY=OFF

# Install newer CMake
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -sSL https://github.com/Kitware/CMake/releases/download/v3.14.1/cmake-3.14.1-Linux-x86_64.tar.gz -o cmake.tar.gz;
      sudo tar xf cmake.tar.gz --strip 1 -C /usr/local;
    else
      brew uninstall cmake;
      curl -sSL https://github.com/Kitware/CMake/releases/download/v3.14.1/cmake-3.14.1-Darwin-x86_64.tar.gz -o cmake.tar.gz;
      sudo tar xf cmake.tar.gz --strip 1 -C /Applications;
      sudo /Applications/CMake.app/Contents/bin/cmake-gui --install;
    fi;
    export PATH=/usr/local/bin:$PATH;

script:
  - cmake
      -B build
      -S .
      -DCMAKE_BUILD_TYPE=Debug
      -DBUILD_SHARED_LIBS=ON
      -DREPROC++=ON
      -DREPROC_TESTS=ON
      -DREPROC_EXAMPLES=ON
      -DREPROC_WARNINGS_AS_ERRORS=ON
      -DREPROC_TIDY=$REPROC_TIDY
      -DREPROC_SANITIZERS=ON
  - cmake --build build --parallel 2
  - build/tests
  # Make sure the examples don't crash or return a non-zero exit code.
  - build/reproc/examples/git-status > /dev/null
  - build/reproc++/examples/cmake-help > /dev/null
