dist: xenial
# We use the generic language to prevent Travis from overwriting the CC and CXX
# environment variables. See https://stackoverflow.com/questions/35110123/travis-ci-with-c14-and-linux.
language: generic

# Leak Sanitizer crashes if we don't run with root priviliges.
sudo: true

notifications:
  email: false

matrix:
  fast_finish: true

env: REPROC_TIDY=ON REPROC_VFORK=OFF

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CC=gcc-5 CXX=g++-5

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: CC=gcc-8 CXX=g++-8

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env: CC=gcc-9 CXX=g++-9 REPROC_VFORK=ON

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
      env: CC=clang-6.0 CXX=clang++-6.0

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
      env: CC=clang-8 CXX=clang++-8 REPROC_VFORK=ON

    - os: osx
      osx_image: xcode10
      env: CC=clang CXX=clang++ REPROC_TIDY=OFF REPROC_VFORK=ON

install:
  # Download CMake manually because brew is too slow on MacOS and Xenial's
  # CMake package is outdated.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -sSL https://github.com/Kitware/CMake/releases/download/v3.13.5/cmake-3.13.5-Linux-x86_64.tar.gz -o cmake.tar.gz;
      sudo tar xf cmake.tar.gz --strip 1 -C /usr/local;
    else
      brew uninstall cmake;
      curl -sSL https://github.com/Kitware/CMake/releases/download/v3.13.5/cmake-3.13.5-Darwin-x86_64.tar.gz -o cmake.tar.gz;
      sudo tar xf cmake.tar.gz --strip 1 -C /Applications;
      sudo /Applications/CMake.app/Contents/bin/cmake-gui --install;
    fi;
    export PATH=/usr/local/bin:$PATH;

script:
  - cmake
      -B build
      -S .
      -DCMAKE_BUILD_TYPE=Debug
      -DBUILD_SHARED_LIBS=ON
      -DREPROC++=ON
      -DREPROC_TEST=ON
      -DREPROC_EXAMPLES=ON
      -DREPROC_WARNINGS_AS_ERRORS=ON
      -DREPROC_TIDY=$REPROC_TIDY
      -DREPROC_SANITIZERS=ON
      -DREPROC_VFORK=$REPROC_VFORK
  - cmake --build build --parallel 2
  - build/test
  # Make sure the examples don't crash or return a non-zero exit code.
  - build/reproc/examples/drain > /dev/null
  - build/reproc/examples/git-status > /dev/null
  - build/reproc++/examples/background cmake --help > /dev/null
  - build/reproc++/examples/cmake-help > /dev/null
  - build/reproc++/examples/forward cmake --help > /dev/null
