name: CI

on: push

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # Github Actions requires a single row to be added to the build matrix.
        # See https://help.github.com/en/articles/workflow-syntax-for-github-actions.
        name: [
          ubuntu-18.04-gcc-4.8,
          ubuntu-18.04-gcc-9,
          ubuntu-18.04-clang-4.0,
          ubuntu-18.04-clang-9,
          windows-2016-cl,
          windows-2016-clang-cl,
          windows-2016-clang,
          windows-2016-gcc,
          windows-2019-cl,
          windows-2019-clang-cl,
          windows-2019-clang,
          windows-2019-gcc,
          macOS-10.14-xcode-10.0,
          macOS-10.14-xcode-10.3
        ]

        include:
          - name: ubuntu-18.04-gcc-4.8
            os: ubuntu-18.04
            compiler: gcc
            version: "6"

          - name: ubuntu-18.04-gcc-9
            os: ubuntu-18.04
            compiler: gcc
            version: "9"

          - name: ubuntu-18.04-clang-4.0
            os: ubuntu-18.04
            compiler: clang
            version: "6.0"

          - name: ubuntu-18.04-clang-9
            os: ubuntu-18.04
            compiler: clang
            version: "9"

          - name: windows-2016-cl
            os: windows-2016
            compiler: cl

          - name: windows-2016-clang-cl
            os: windows-2016
            compiler: clang-cl

          - name: windows-2016-clang
            os: windows-2016
            compiler: clang

          - name: windows-2016-gcc
            os: windows-2016
            compiler: gcc

          - name: windows-2019-cl
            os: windows-2019
            compiler: cl

          - name: windows-2019-clang-cl
            os: windows-2019
            compiler: clang-cl

          - name: windows-2019-clang
            os: windows-2019
            compiler: clang

          - name: windows-2019-gcc
            os: windows-2019
            compiler: gcc

          - name: macOS-10.14-xcode-10.0
            os: macOS-10.14
            compiler: xcode
            version: "10"

          - name: macOS-10.14-xcode-10.3
            os: macOS-10.14
            compiler: xcode
            version: "10.3"

    steps:
      - uses: actions/checkout@v1

      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          curl -sSL https://github.com/Kitware/CMake/releases/download/v3.13.5/cmake-3.13.5-Linux-x86_64.tar.gz -o cmake.tar.gz
          sudo tar xf cmake.tar.gz --strip 1 -C /usr/local

          # LLVM 9 is not yet in bionic's repositories.
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
          sudo apt-get update

          sudo apt-get install -y ninja-build clang-tidy-9
          sudo ln -s /usr/bin/clang-tidy-9 /usr/local/bin/clang-tidy

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++-${{ matrix.version }}
            echo "::set-env name=CC::gcc-${{ matrix.version }}"
            echo "::set-env name=CXX::g++-${{ matrix.version }}"
          else
            sudo apt-get install -y clang-${{ matrix.version }}
            echo "::set-env name=CC::clang-${{ matrix.version }}"
            echo "::set-env name=CXX::clang++-${{ matrix.version }}"
          fi

          # Allows us to use `> NUL` as a cross platform way to discard output
          # from examples.
          sudo ln -s /dev/null NUL

      - name: Install (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install ninja llvm
          sudo ln -s /usr/local/opt/llvm/bin/clang-tidy /usr/local/bin/clang-tidy

          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app

          echo "::set-env name=CC::clang"
          echo "::set-env name=CXX::clang++"

          sudo ln -s /dev/null NUL

      - name: Install (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
          scoop install ninja llvm --global

          if ("${{ matrix.compiler }}" -eq "gcc") {
            echo "::set-env name=CC::gcc"
            echo "::set-env name=CXX::g++"
          } elseif ("${{ matrix.compiler }}" -eq "clang") {
            echo "::set-env name=CC::clang"
            echo "::set-env name=CXX::clang++"
          } else {
            echo "::set-env name=CC::${{ matrix.compiler }}"
            echo "::set-env name=CXX::${{ matrix.compiler }}"
          }

          # We add the output directories to the PATH to make sure the tests and
          # examples can find the reproc and reproc++ DLL's.
          $env:PATH += ";$pwd\build\reproc\lib"
          $env:PATH += ";$pwd\build\reproc++\lib"

          & .github\workflows\vsenv.bat -arch=x64 -host_arch=x64

      # We build reproc as a shared library to verify all the necessary symbols
      # are exported.

      # YAML folded multiline strings ('>') require the same indentation for all
      # lines in order to turn newlines into spaces.

      - name: Configure
        run: >
          cmake
          -B build
          -S .
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_SHARED_LIBS=ON
          -DREPROC++=ON
          -DREPROC_TEST=ON
          -DREPROC_EXAMPLES=ON
          -DREPROC_WARNINGS_AS_ERRORS=ON
          -DREPROC_TIDY=ON

      - name: Configure Sanitizers (Linux && macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: cmake build -DREPROC_SANITIZERS=ON

      - name: Build
        run: cmake --build build

      # Aside from running the tests we also make sure the examples don't
      # crash or return a non-zero exit code.

      # When surrounding an executable path with quotes, we can use forward
      # slashes in cmd.exe.

      - name: Test
        run: |
          "build/test"

          "build/reproc/examples/drain" > NUL
          "build/reproc/examples/git-status" > NUL
          "build/reproc++/examples/background" cmake --help > NUL
          "build/reproc++/examples/cmake-help" > NUL
          "build/reproc++/examples/forward" cmake --help > NUL
